<?xml version="1.0" encoding="utf-8"?><Database Name="dbIR" Class="IRContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=dbIR;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbIR" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CrisisCode" Member="CrisisCodes">
    <Type Name="CrisisCode">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="CrisisCode_IRTransaction" Member="IRTransactions" ThisKey="Id" OtherKey="CrisisId" Type="IRTransaction" />
    </Type>
  </Table>
  <Table Name="dbo.EvidencePhoto" Member="EvidencePhotos">
    <Type Name="EvidencePhoto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IrId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="IRTransaction_EvidencePhoto" Member="IRTransaction" ThisKey="IrId" OtherKey="Id" Type="IRTransaction" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.SiteStatus" Member="SiteStatus">
    <Type Name="SiteStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DepartmentsInvolved" Member="DepartmentsInvolveds">
    <Type Name="DepartmentsInvolved">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IRId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="IRTransaction_DepartmentsInvolved" Member="IRTransaction" ThisKey="IRId" OtherKey="Id" Type="IRTransaction" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.IRTransaction" Member="IRTransactions">
    <Type Name="IRTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CrisisId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[From]" Member="From" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WhenIncidentHappen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WhenAware" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WhoInvolved" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WhatHappened" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Investigation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ActionTaken" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Recommendation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PreparedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateSolved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="IRTransaction_EvidencePhoto" Member="EvidencePhotos" ThisKey="Id" OtherKey="IrId" Type="EvidencePhoto" />
      <Association Name="IRTransaction_DepartmentsInvolved" Member="DepartmentsInvolveds" ThisKey="Id" OtherKey="IRId" Type="DepartmentsInvolved" />
      <Association Name="CrisisCode_IRTransaction" Member="CrisisCode" ThisKey="CrisisId" OtherKey="Id" Type="CrisisCode" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>